name: learningmanagement
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  device_info_plus: ^12.2.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_database: ^12.0.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  flutter_riverpod: ^3.0.3
  permission_handler: ^12.0.1
  table_calendar: ^3.2.0
  timezone: ^0.10.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
